services:
  redis:
    image: redis:8.6-alpine3.23
    container_name: redis-broker
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  emailservice:
    build: .
    container_name: emailservice
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
